# Generated by Django 3.0.8 on 2020-08-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='slug',
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
