# Generated by Django 3.0.8 on 2020-08-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20200802_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_group',
            new_name='category',
        ),
    ]
