# Generated by Django 3.0.8 on 2020-08-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20200805_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
