# Generated by Django 3.0.8 on 2020-07-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_id', models.TextField()),
                ('slider_img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('slider_text', models.TextField()),
                ('slider_title', models.CharField(max_length=120)),
                ('article_text', models.TextField()),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
