# Generated by Django 3.0.8 on 2020-07-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_auto_20200730_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.TextField()),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_id', models.TextField()),
                ('slider_img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('slider_text', models.TextField()),
                ('slider_title', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Content_Main',
        ),
    ]
