# Generated by Django 3.0.8 on 2020-07-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_delete_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider_text',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider_title',
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_discount_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
