# Generated by Django 3.0.8 on 2020-07-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0006_auto_20200730_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_discount_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
