# Generated by Django 3.0.8 on 2020-07-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0010_auto_20200731_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_discount_date_main',
            field=models.DurationField(verbose_name='20200731'),
        ),
    ]
