# Generated by Django 3.0.8 on 2020-07-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0011_auto_20200731_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider_discount_date_main',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider_id',
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_first',
            field=models.BooleanField(default=False),
        ),
    ]
