# Generated by Django 3.0.8 on 2020-07-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0012_auto_20200731_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
