# Generated by Django 3.0.8 on 2020-08-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0013_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider_first',
        ),
    ]
